/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoIntegrador;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Propietario
 */
public class pryIntegradorFrame extends javax.swing.JFrame {
    
    DefaultTableModel modelo;
    String[] columnNames={"Matricula","DNI","Nombre","Apellido","Direccion","Correo","Telefono","Año","Curso","Especialidad"};
    int fila = 0;
    List<Dato> lista = new ArrayList<>();
    
    

    /**
     * Creates new form pryIntegradorFrame
     */
    public pryIntegradorFrame() {
        initComponents();
        modelo=new DefaultTableModel(columnNames,fila);
        tabla.setModel(modelo);
     
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMatricula = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDni = new javax.swing.JTextArea();
        sp = new javax.swing.JScrollPane();
        txtNombre = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtApellido = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDireccion = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtEmail = new javax.swing.JTextArea();
        sp2 = new javax.swing.JScrollPane();
        txtTelefono = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtAño = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtCurso = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtEspecialidad = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnBuscarMat = new javax.swing.JButton();
        btnBuscarDni = new javax.swing.JButton();
        btnBuscarAp = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDesarrolladores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMatricula.setColumns(20);
        txtMatricula.setRows(1);
        txtMatricula.setText("Ingrese su Matricula");
        jScrollPane1.setViewportView(txtMatricula);

        txtDni.setColumns(20);
        txtDni.setRows(1);
        txtDni.setText("Ingrese su DNI");
        txtDni.setToolTipText("");
        jScrollPane2.setViewportView(txtDni);

        txtNombre.setColumns(20);
        txtNombre.setRows(1);
        txtNombre.setText("Ingrese su Nombre");
        sp.setViewportView(txtNombre);

        txtApellido.setColumns(20);
        txtApellido.setRows(1);
        txtApellido.setText("Ingrese su Apellido");
        jScrollPane3.setViewportView(txtApellido);

        txtDireccion.setColumns(20);
        txtDireccion.setRows(1);
        txtDireccion.setText("Ingrese su Direccion");
        jScrollPane4.setViewportView(txtDireccion);

        txtEmail.setColumns(20);
        txtEmail.setRows(1);
        txtEmail.setText("Ingrese su correo electronico");
        jScrollPane5.setViewportView(txtEmail);

        txtTelefono.setColumns(20);
        txtTelefono.setRows(1);
        txtTelefono.setText("Ingrese su telefono");
        sp2.setViewportView(txtTelefono);

        txtAño.setColumns(20);
        txtAño.setRows(1);
        txtAño.setText("Ingrese su año");
        jScrollPane6.setViewportView(txtAño);

        txtCurso.setColumns(20);
        txtCurso.setRows(1);
        txtCurso.setText("Ingrese su curso");
        txtCurso.setToolTipText("");
        jScrollPane7.setViewportView(txtCurso);

        txtEspecialidad.setColumns(20);
        txtEspecialidad.setRows(1);
        txtEspecialidad.setText("Ingrese su Especialidad");
        jScrollPane8.setViewportView(txtEspecialidad);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "DNI", "Nombre", "Apellido", "Direccion", "Correo ", "Telefono", "Año", "Curso", "Especialidad"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tabla);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBaja.setText("Dar de baja");
        btnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaActionPerformed(evt);
            }
        });

        btnBuscarMat.setText("Buscar");
        btnBuscarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMatActionPerformed(evt);
            }
        });

        btnBuscarDni.setText("Buscar");
        btnBuscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDniActionPerformed(evt);
            }
        });

        btnBuscarAp.setText("Buscar");
        btnBuscarAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarApActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnDesarrolladores.setText("DESARROLLADORES");
        btnDesarrolladores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesarrolladoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addComponent(sp)
                        .addComponent(jScrollPane3)
                        .addComponent(jScrollPane4)
                        .addComponent(jScrollPane5)
                        .addComponent(sp2)
                        .addComponent(jScrollPane6)
                        .addComponent(jScrollPane7)
                        .addComponent(jScrollPane8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(20, 20, 20)
                        .addComponent(btnEditar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarMat)
                            .addComponent(btnBuscarDni)
                            .addComponent(btnBuscarAp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBaja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDesarrolladores)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarMat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarDni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarAp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sp2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnBaja)
                    .addComponent(btnEditar)
                    .addComponent(btnDesarrolladores))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        Dato dato = new Dato(txtMatricula.getText(),
                txtDni.getText(),
                txtNombre.getText(),
                txtApellido.getText(),
                txtDireccion.getText(),
                txtEmail.getText(),
                txtTelefono.getText(),
                txtAño.getText(),
                txtCurso.getText(),
                txtEspecialidad.getText());
        
        lista.add(dato);
        
        modelo.setRowCount(0);
        
        for (int i=0;i<lista.size();i++){
            System.out.println(lista.get(i));
            Object[] objFila={lista.get(i).getMatricula(),
                lista.get(i).getDni(),
                lista.get(i).getNombre(),
                lista.get(i).getApellido(),
                lista.get(i).getDireccion(),
                lista.get(i).getEmail(),
                lista.get(i).getTelefono(),
                lista.get(i).getAño(),
                lista.get(i).getCurso(),
                lista.get(i).getEspecialidad()};
            modelo.addRow(objFila);
        }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        modelo.removeRow(fila);
        lista.remove(fila);
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnBuscarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMatActionPerformed
        modelo.setRowCount(0);
        
        for (int i=0;i<lista.size();i++){
            System.out.println(lista.get(i));
            Object[] objFila={lista.get(i).getMatricula(),
                lista.get(i).getDni(),
                lista.get(i).getNombre(),
                lista.get(i).getApellido(),
                lista.get(i).getDireccion(),
                lista.get(i).getEmail(),
                lista.get(i).getTelefono(),
                lista.get(i).getAño(),
                lista.get(i).getCurso(),
                lista.get(i).getEspecialidad()};
            
            if(lista.get(i).getMatricula().startsWith(txtMatricula.getText())){
                modelo.addRow(objFila);
            }
                
            
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMatActionPerformed

    private void btnBuscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDniActionPerformed
        modelo.setRowCount(0);
        
        for (int i=0;i<lista.size();i++){
            System.out.println(lista.get(i));
            Object[] objFila={lista.get(i).getMatricula(),
                lista.get(i).getDni(),
                lista.get(i).getNombre(),
                lista.get(i).getApellido(),
                lista.get(i).getDireccion(),
                lista.get(i).getEmail(),
                lista.get(i).getTelefono(),
                lista.get(i).getAño(),
                lista.get(i).getCurso(),
                lista.get(i).getEspecialidad()};
            
            if(lista.get(i).getDni().startsWith(txtDni.getText())){
                modelo.addRow(objFila);
            }
            }
    }//GEN-LAST:event_btnBuscarDniActionPerformed

    private void btnBuscarApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarApActionPerformed
        modelo.setRowCount(0);
        
        for (int i=0;i<lista.size();i++){
            System.out.println(lista.get(i));
            Object[] objFila={lista.get(i).getMatricula(),
                lista.get(i).getDni(),
                lista.get(i).getNombre(),
                lista.get(i).getApellido(),
                lista.get(i).getDireccion(),
                lista.get(i).getEmail(),
                lista.get(i).getTelefono(),
                lista.get(i).getAño(),
                lista.get(i).getCurso(),
                lista.get(i).getEspecialidad()};
            
            if(lista.get(i).getApellido().startsWith(txtApellido.getText())){
                modelo.addRow(objFila);
            }
    }//GEN-LAST:event_btnBuscarApActionPerformed
}
    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        fila= tabla.getSelectedRow();
        
        txtMatricula.setText(String.valueOf(modelo.getValueAt(fila,0)));
        txtDni.setText(String.valueOf(modelo.getValueAt(fila,1)));
        txtNombre.setText(String.valueOf(modelo.getValueAt(fila,2)));
        txtApellido.setText(String.valueOf(modelo.getValueAt(fila,3)));
        txtDireccion.setText(String.valueOf(modelo.getValueAt(fila,4)));
        txtEmail.setText(String.valueOf(modelo.getValueAt(fila,5)));
        txtTelefono.setText(String.valueOf(modelo.getValueAt(fila,6)));
        txtAño.setText(String.valueOf(modelo.getValueAt(fila,7)));
        txtCurso.setText(String.valueOf(modelo.getValueAt(fila,8)));
        txtEspecialidad.setText(String.valueOf(modelo.getValueAt(fila,9)));
    }//GEN-LAST:event_tablaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        lista.get(fila).setMatricula(txtMatricula.getText());
        lista.get(fila).setDni(txtDni.getText());
        lista.get(fila).setNombre(txtNombre.getText());
        lista.get(fila).setApellido(txtApellido.getText());
        lista.get(fila).setDireccion(txtDireccion.getText());
        lista.get(fila).setEmail(txtEmail.getText());
        lista.get(fila).setTelefono(txtTelefono.getText());
        lista.get(fila).setAño(txtAño.getText());
        lista.get(fila).setCurso(txtCurso.getText());
        lista.get(fila).setEspecialidad(txtEspecialidad.getText());
        
        modelo.setRowCount(0);
        
        for (int i=0;i<lista.size();i++){
            System.out.println(lista.get(i));
            Object[] objFila={lista.get(i).getMatricula(),
                lista.get(i).getDni(),
                lista.get(i).getNombre(),
                lista.get(i).getApellido(),
                lista.get(i).getDireccion(),
                lista.get(i).getEmail(),
                lista.get(i).getTelefono(),
                lista.get(i).getAño(),
                lista.get(i).getCurso(),
                lista.get(i).getEspecialidad()};
            
            if(lista.get(i).getApellido().startsWith(txtApellido.getText())){
                modelo.addRow(objFila);
            }
    }     
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDesarrolladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesarrolladoresActionPerformed
        JOptionPane.showMessageDialog(null,"Desarrolladores: Feijoo Federico,Infanti Mariano,Virgilio Delfina.\nCurso 7mo3ra :) ");
    }//GEN-LAST:event_btnDesarrolladoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pryIntegradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pryIntegradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pryIntegradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pryIntegradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pryIntegradorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnBuscarAp;
    private javax.swing.JButton btnBuscarDni;
    private javax.swing.JButton btnBuscarMat;
    private javax.swing.JButton btnDesarrolladores;
    private javax.swing.JButton btnEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane sp;
    private javax.swing.JScrollPane sp2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextArea txtApellido;
    private javax.swing.JTextArea txtAño;
    private javax.swing.JTextArea txtCurso;
    private javax.swing.JTextArea txtDireccion;
    private javax.swing.JTextArea txtDni;
    private javax.swing.JTextArea txtEmail;
    private javax.swing.JTextArea txtEspecialidad;
    private javax.swing.JTextArea txtMatricula;
    private javax.swing.JTextArea txtNombre;
    private javax.swing.JTextArea txtTelefono;
    // End of variables declaration//GEN-END:variables
}
